name: github-Linux
on: [push, pull_request]

jobs:
  CI:
    continue-on-error: true
    strategy:
      matrix:
        cxx: ['g++', 'clang++-12']
        cmake_build_type: ['Release', 'Debug']
        cuda: ['yes', 'no']
        mpi: ['yes', 'no']
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/pgrete/parthenon/cuda11.4.2-mpi-hdf5
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: CMake
        run: |
          cmake -B builddir \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DMACHINE_CFG=${PWD}/cmake/machinecfg/GitHubActions.cmake \
            -DMACHINE_VARIANT=cuda-${{ matrix.cuda }}_mpi-${{ matrix.mpi }}
      - name: Build
        run: |
          cmake --build builddir --parallel 2